### ISSUE TITLE
ラインスタンプ

### ISSUE THREAD

**Issue by tomari** [arigato-java/java_images#4]
![screenshot 2017-09-12 at 06 57 40](https://user-images.githubusercontent.com/1059211/30298848-e0b7cf62-9787-11e7-9e53-c1c4d315689f.png)

- [ ] 要件調査
- [ ] アーティストに発注
- [ ] 申請作業

**Comment by Mekajiki** [comment]
要件調査の前に，コンセプトデザイン，世界観の構築・定義が必要ではないでしょうか？

**Comment by tobynet** [comment]
「ジャバは拝承」、「シュール＆ポップな拝承」のイメージの叩き台です

Click to large.

案1, 2:
[![new doc 2017-09-13_1_s](https://user-images.githubusercontent.com/20859/30347321-aa3562e6-9846-11e7-9a26-3ba6a4aacd08.jpg)](https://user-images.githubusercontent.com/20859/30346309-507e4cf2-9843-11e7-85ea-92615671941e.jpg) &nbsp; [![new doc 2017-09-13_2_s](https://user-images.githubusercontent.com/20859/30347320-aa3009b8-9846-11e7-96a0-3d6bedb0e70f.jpg)](https://user-images.githubusercontent.com/20859/30346342-6c848024-9843-11e7-8950-76cd0b888388.jpg)

案3, 4:
[![new doc 2017-09-13_3_s](https://user-images.githubusercontent.com/20859/30347323-aa444c98-9846-11e7-9bda-9c14b5c2a7d3.jpg)](https://user-images.githubusercontent.com/20859/30346346-6f5688f6-9843-11e7-9281-2311116bc1f9.jpg) &nbsp; [![new doc 2017-09-13_4_s](https://user-images.githubusercontent.com/20859/30347319-aa2ab8fa-9846-11e7-8236-5a48577ec93b.jpg)](https://user-images.githubusercontent.com/20859/30346347-71bf5078-9843-11e7-9210-dd19a26cb4cb.jpg)

案5,6:
[![new doc 2017-09-13_5_s](https://user-images.githubusercontent.com/20859/30347322-aa3ecf70-9846-11e7-8de7-f958084cfc0e.jpg)](https://user-images.githubusercontent.com/20859/30346353-73d2d506-9843-11e7-8816-8581ce531792.jpg) &nbsp; [![new doc 2017-09-13_6_s](https://user-images.githubusercontent.com/20859/30347318-aa2a9dd4-9846-11e7-8d21-43bfb682b5d6.jpg)](https://user-images.githubusercontent.com/20859/30346362-76ec4038-9843-11e7-8a5a-0344cfb60361.jpg)

案7, 8:
[![new doc 2017-09-13_7_s](https://user-images.githubusercontent.com/20859/30347327-aa558efe-9846-11e7-98ea-3000aebfc931.jpg)](https://user-images.githubusercontent.com/20859/30346366-79104ae4-9843-11e7-87f2-15df640738d9.jpg) &nbsp; [![new doc 2017-09-13_8_s](https://user-images.githubusercontent.com/20859/30347324-aa546f2e-9846-11e7-997d-6533472d1b18.jpg)](https://user-images.githubusercontent.com/20859/30346370-7a56a218-9843-11e7-8364-81f0dc073407.jpg)

案9, 10:
[![new doc 2017-09-13_9_s](https://user-images.githubusercontent.com/20859/30347329-aa57473a-9846-11e7-9f4a-0a05c8e0d509.jpg)](https://user-images.githubusercontent.com/20859/30346375-7c060cca-9843-11e7-8d06-c729726353f4.jpg) &nbsp; [![new doc 2017-09-13_10_s](https://user-images.githubusercontent.com/20859/30347332-aa718776-9846-11e7-8987-e76e4830c813.jpg)](https://user-images.githubusercontent.com/20859/30346379-7d1e5dec-9843-11e7-8d68-c902f1391ac2.jpg)

**Comment by tomari** [comment]
ありがとうございます。一部モーション付ける必要がありそうです。
入稿フォーマットを調査してからですが、Spine が使えれば楽なのですが。

**Comment by tomari** [comment]
入稿フォーマットはPNG/APNGだそうです。
その他ガイドラインはこちら
https://creator.line.me/ja/guideline/animationsticker/

**Comment by tomari** [comment]
@tobynet １を画像化してみたのですが、いまひとつパッとしません。スタイル的な部分で指導いただけませんか。
![2018-01-11 21 39 49](https://user-images.githubusercontent.com/1059211/34825982-1a0e3f5e-f718-11e7-918f-813c088473af.png)

**Comment by tobynet** [comment]
* 既存のフォント + イラレで編集がいいかなと思っています。
* もしくは、古典的 WordArt を活用するのがいいかもしれません

一旦、知人のデザイナさんに相談してみます（別件があるので、すぐにはすすまないかも。。。）

**Comment by tomari** [comment]
進捗：事務的な部分を済ませ、アカウントを取得し投稿できる段階まで持ってきました

**Comment by tobynet** [comment]
社会状況等あり、こちらのデザイナさんとの連絡含め、進捗のめどが立っておりません。

最初のバージョンとして、一度リリース手続きしてみて頂けないでしょうか。 スタンプの審査等あったと思いますので、問題点を洗い出す機会にもなると思います。

**Comment by tomari** [comment]
一旦、ジャバ組と悟られないよう、無関係な内容ですべてのアセットを揃え、投稿してみました。
![2018-01-27 11 36 56](https://user-images.githubusercontent.com/1059211/35467782-8703d912-0356-11e8-93bf-3bf1209f3910.png)

**Comment by tobynet** [comment]
一通りの流れを試すのは、よいですね。

**Comment by tomari** [comment]
背景の透明度などで審査結果：却下となったため、修正して再投稿しました。

**Comment by tomari** [comment]
発売開始しました

**Comment by tobynet** [comment]
確認いたしました！！ 利用可能なようです。

**Comment by tobynet** [comment]
今、こちらのデザイナさんに、1枚試しに作っていただいています

**Comment by tobynet** [comment]
デザイナさんにサンプルを作ってもらったのを貼ります
![e5ca054c-b743-415a-a13c-ef602f5868ae](https://user-images.githubusercontent.com/20859/37255688-2201dc62-2593-11e8-9174-9eb4b3adcea6.png)

![2404a4b5-04e8-4de6-b855-3936be508da0](https://user-images.githubusercontent.com/20859/37255689-25b7966c-2593-11e8-8ab4-c1c833736937.png)

**Comment by tobynet** [comment]
こちらでも打ち合わせ中に、いくつか作ってみました
![default](https://user-images.githubusercontent.com/20859/37255728-e339fb26-2593-11e8-872d-91b83eee86df.png) 
![default](https://user-images.githubusercontent.com/20859/37255729-e68b2430-2593-11e8-8f07-8e500b2bcb0a.png) ![default](https://user-images.githubusercontent.com/20859/37255730-eaff9078-2593-11e8-8018-fe0e4688ac8e.png)

----
![default](https://user-images.githubusercontent.com/20859/37255733-f4c67e8c-2593-11e8-8f7b-c1c94f616c70.png) 
![default](https://user-images.githubusercontent.com/20859/37255736-f7d16a42-2593-11e8-8e13-6fb8542f6b5e.png)
![default](https://user-images.githubusercontent.com/20859/37255737-fad27e20-2593-11e8-939e-0acf52212f8d.png)

----
![default](https://user-images.githubusercontent.com/20859/37255740-ff55798e-2593-11e8-9063-b6edc334bc01.png)  ![2](https://user-images.githubusercontent.com/20859/37255742-03ef2878-2594-11e8-8409-93de69e9f3f4.png)

**Comment by tobynet** [comment]
メイン画像、タブ画像向けはこれかな。 
![main240px](https://user-images.githubusercontent.com/20859/37255760-56d0deb0-2594-11e8-9a5f-29a58efe1711.png)

**Comment by tobynet** [comment]
こちらの打合わせの中で、「フォントや必要な文字を決めると進めやすい」ことが分かり、その方向で試作しています。

また、先のデザイナさんによるサンプルのように、文字の色やエフェクトにより感情表現が行えるようです。
「ジャバ」だけで8つあるようなバージョンもリリース可能だと思います。

**Comment by tomari** [comment]
皆様、

こちら、ラインスタンプでは上記のようにリジェクトになり難しそうですが、シグナルのステッカーなら行けそうです。
近いうちに投稿してみます。

**Comment by tomari** [comment]
Signalのステッカー利用可能
https://signal.art/addstickers/#pack_id=cd4dbeee3cd190ce6e877df41ce0e550&pack_key=8bf096db7e91bbd0c5de67f3367cf5305972c312b42aff93838b8926acceb2d1

**Comment by tomari** [comment]
Telegramのステッカー利用可能
https://t.me/addstickers/AnatatoJava
